
#define _CLC_RELATIONAL_DECL_VECTOR(RET_TYPE, FUNCTION, ARG_TYPE) \
  _CLC_OVERLOAD _CLC_DECL RET_TYPE##2 FUNCTION(ARG_TYPE##2, ARG_TYPE##2); \
  _CLC_OVERLOAD _CLC_DECL RET_TYPE##3 FUNCTION(ARG_TYPE##3, ARG_TYPE##3); \
  _CLC_OVERLOAD _CLC_DECL RET_TYPE##4 FUNCTION(ARG_TYPE##4, ARG_TYPE##4); \
  _CLC_OVERLOAD _CLC_DECL RET_TYPE##8 FUNCTION(ARG_TYPE##8, ARG_TYPE##8); \
  _CLC_OVERLOAD _CLC_DECL RET_TYPE##16 FUNCTION(ARG_TYPE##16, ARG_TYPE##16);

#define _CLC_RELATIONAL_DECL_SCALAR(RET_TYPE, FUNCTION, ARG_TYPE) \
  _CLC_OVERLOAD _CLC_DECL RET_TYPE FUNCTION(ARG_TYPE, ARG_TYPE);

#define _CLC_RELATIONAL_DECL_ALL(RET_TYPE, FUNCTION, ARG_TYPE) \
  _CLC_RELATIONAL_DECL_SCALAR(RET_TYPE, FUNCTION, ARG_TYPE) \
  _CLC_RELATIONAL_DECL_VECTOR(RET_TYPE, FUNCTION, ARG_TYPE)

_CLC_RELATIONAL_DECL_ALL(int, isequal, float)
_CLC_RELATIONAL_DECL_ALL(int, isnotequal, float)
_CLC_RELATIONAL_DECL_ALL(int, isgreater, float)
_CLC_RELATIONAL_DECL_ALL(int, isgreaterequal, float)
_CLC_RELATIONAL_DECL_ALL(int, isless, float)
_CLC_RELATIONAL_DECL_ALL(int, islessequal, float)
_CLC_RELATIONAL_DECL_ALL(int, islessgreater, float)
_CLC_RELATIONAL_DECL_ALL(int, isordered, float)
_CLC_RELATIONAL_DECL_ALL(int, isunordered, float)

