
#define _CLC_ISLESSGREATER_DECL(RET_TYPE, ARG_TYPE) \
  _CLC_OVERLOAD _CLC_DECL RET_TYPE islessgreater(ARG_TYPE, ARG_TYPE);

#define _CLC_VECTOR_ISLESSGREATER_DECL(RET_TYPE, ARG_TYPE) \
  _CLC_ISLESSGREATER_DECL(RET_TYPE##2, ARG_TYPE##2) \
  _CLC_ISLESSGREATER_DECL(RET_TYPE##3, ARG_TYPE##3) \
  _CLC_ISLESSGREATER_DECL(RET_TYPE##4, ARG_TYPE##4) \
  _CLC_ISLESSGREATER_DECL(RET_TYPE##8, ARG_TYPE##8) \
  _CLC_ISLESSGREATER_DECL(RET_TYPE##16, ARG_TYPE##16)

_CLC_ISLESSGREATER_DECL(int, float)
_CLC_VECTOR_ISLESSGREATER_DECL(int, float)

#ifdef cl_khr_fp64
_CLC_ISLESSGREATER_DECL(int, double)
_CLC_VECTOR_ISLESSGREATER_DECL(long, double)
#endif

#undef _CLC_ISLESSGREATER_DECL
#undef _CLC_VECTOR_ISLESSGREATER_DECL
