#define _CLC_RELATIONAL_BINARY_VECTORIZE(DECLSPEC, RET_TYPE, FUNCTION, ARG1_TYPE, ARG2_TYPE) \
  DECLSPEC RET_TYPE##2 FUNCTION(ARG1_TYPE##2 x, ARG2_TYPE##2 y) { \
    return (RET_TYPE##2)(FUNCTION##_rel(x.x, y.x), FUNCTION##_rel(x.y, y.y)); \
  } \
\
  DECLSPEC RET_TYPE##3 FUNCTION(ARG1_TYPE##3 x, ARG2_TYPE##3 y) { \
    return (RET_TYPE##3)(FUNCTION##_rel(x.x, y.x), FUNCTION##_rel(x.y, y.y), \
                         FUNCTION##_rel(x.z, y.z)); \
  } \
\
  DECLSPEC RET_TYPE##4 FUNCTION(ARG1_TYPE##4 x, ARG2_TYPE##4 y) { \
    return (RET_TYPE##4)(FUNCTION(x.lo, y.lo), FUNCTION(x.hi, y.hi)); \
  } \
\
  DECLSPEC RET_TYPE##8 FUNCTION(ARG1_TYPE##8 x, ARG2_TYPE##8 y) { \
    return (RET_TYPE##8)(FUNCTION(x.lo, y.lo), FUNCTION(x.hi, y.hi)); \
  } \
\
  DECLSPEC RET_TYPE##16 FUNCTION(ARG1_TYPE##16 x, ARG2_TYPE##16 y) { \
    return (RET_TYPE##16)(FUNCTION(x.lo, y.lo), FUNCTION(x.hi, y.hi)); \
  }

#define _CLC_RELATIONAL_DEFINE_BINARY_BUILTIN(RET_TYPE, FUNCTION, BUILTIN, ARG1_TYPE, ARG2_TYPE) \
_CLC_DEF _CLC_OVERLOAD RET_TYPE FUNCTION(ARG1_TYPE x, ARG2_TYPE y) { \
  return BUILTIN(x, y); \
} \
_CLC_DEF _CLC_OVERLOAD RET_TYPE FUNCTION##_rel(ARG1_TYPE x, ARG2_TYPE y) { \
  return ~(BUILTIN(x, y)-1); \
} \
_CLC_RELATIONAL_BINARY_VECTORIZE(_CLC_OVERLOAD _CLC_DEF, RET_TYPE, FUNCTION, ARG1_TYPE, ARG2_TYPE)

#define _CLC_RELATIONAL_DEFINE_BINARY_BUILTIN_FP64(RET_TYPE_32, RET_TYPE_64, FUNCTION, BUILTIN, ARG_TYPE) \
_CLC_DEF _CLC_OVERLOAD RET_TYPE_32 FUNCTION(ARG_TYPE x, ARG_TYPE y) { \
  return BUILTIN(x, y); \
} \
_CLC_DEF _CLC_OVERLOAD RET_TYPE_64 FUNCTION##_rel(ARG_TYPE x, ARG_TYPE y) { \
  return ~(BUILTIN(x, y)-1); \
} \
_CLC_RELATIONAL_BINARY_VECTORIZE(_CLC_OVERLOAD _CLC_DEF, RET_TYPE_64, FUNCTION, ARG_TYPE, ARG_TYPE)


#define _CLC_RELATIONAL_UNARY_VECTORIZE(DECLSPEC, RET_TYPE, FUNCTION, ARG1_TYPE) \
  DECLSPEC RET_TYPE##2 FUNCTION(ARG1_TYPE##2 x) { \
    return (RET_TYPE##2)(FUNCTION##_rel(x.x), FUNCTION##_rel(x.y)); \
  } \
\
  DECLSPEC RET_TYPE##3 FUNCTION(ARG1_TYPE##3 x) { \
    return (RET_TYPE##3)(FUNCTION##_rel(x.x), FUNCTION##_rel(x.y), \
                         FUNCTION##_rel(x.z)); \
  } \
\
  DECLSPEC RET_TYPE##4 FUNCTION(ARG1_TYPE##4 x) { \
    return (RET_TYPE##4)(FUNCTION(x.lo), FUNCTION(x.hi)); \
  } \
\
  DECLSPEC RET_TYPE##8 FUNCTION(ARG1_TYPE##8 x) { \
    return (RET_TYPE##8)(FUNCTION(x.lo), FUNCTION(x.hi)); \
  } \
\
  DECLSPEC RET_TYPE##16 FUNCTION(ARG1_TYPE##16 x) { \
    return (RET_TYPE##16)(FUNCTION(x.lo), FUNCTION(x.hi)); \
  }

#define _CLC_RELATIONAL_DEFINE_UNARY_BUILTIN(RET_TYPE, FUNCTION, BUILTIN, ARG1_TYPE) \
_CLC_DEF _CLC_OVERLOAD RET_TYPE FUNCTION(ARG1_TYPE x) { \
  return BUILTIN(x); \
} \
_CLC_DEF _CLC_OVERLOAD RET_TYPE FUNCTION##_rel(ARG1_TYPE x) { \
  return ~(BUILTIN(x)-1); \
} \
_CLC_RELATIONAL_UNARY_VECTORIZE(_CLC_OVERLOAD _CLC_DEF, RET_TYPE, FUNCTION, ARG1_TYPE)

